export const customers = [
  {
    id: "1",
    name: "Salman Siddiqui",
    email: "siddiquisalman324@gmail.com",
  },
];

export const accounts = [
  {
    id: "1",
    customerId: "1",
    accountNumber: "1234567890",
    balance: 75000.5,
    currency: "USD",
  },
];

export const transactions = [
  {
    id: "1",
    accountId: "1",
    type: "CREDIT",
    amount: 250.0,
    description: "Salary Deposit",
    date: new Date().toISOString(),
  },
  {
    id: "2",
    accountId: "1",
    type: "DEBIT",
    amount: 75.5,
    description: "Grocery Shopping",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    accountId: "1",
    type: "DEBIT",
    amount: 120.99,
    description: "Electricity Bill Payment",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    accountId: "1",
    type: "CREDIT",
    amount: 150.0,
    description: "Refund from Vendor",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    accountId: "1",
    type: "DEBIT",
    amount: 45.0,
    description: "Restaurant Dinner",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    accountId: "1",
    type: "DEBIT",
    amount: 20.0,
    description: "Mobile Recharge",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    accountId: "1",
    type: "CREDIT",
    amount: 500.0,
    description: "Freelance Project Payment",
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    accountId: "1",
    type: "DEBIT",
    amount: 35.0,
    description: "Gas Station",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "9",
    accountId: "1",
    type: "DEBIT",
    amount: 60.0,
    description: "Netflix Subscription",
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "10",
    accountId: "1",
    type: "CREDIT",
    amount: 100.0,
    description: "Gift from Friend",
    date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "11",
    accountId: "1",
    type: "DEBIT",
    amount: 80.0,
    description: "Gym Membership",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "12",
    accountId: "1",
    type: "CREDIT",
    amount: 300.0,
    description: "Stock Dividend",
    date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "13",
    accountId: "1",
    type: "DEBIT",
    amount: 95.0,
    description: "Online Shopping - Amazon",
    date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "14",
    accountId: "1",
    type: "DEBIT",
    amount: 15.0,
    description: "Coffee Shop",
    date: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "15",
    accountId: "1",
    type: "CREDIT",
    amount: 400.0,
    description: "Bonus Payment",
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "16",
    accountId: "1",
    type: "DEBIT",
    amount: 250.0,
    description: "Travel Tickets",
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "17",
    accountId: "1",
    type: "CREDIT",
    amount: 50.0,
    description: "Cashback from Credit Card",
    date: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "18",
    accountId: "1",
    type: "DEBIT",
    amount: 32.0,
    description: "Book Purchase",
    date: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "19",
    accountId: "1",
    type: "CREDIT",
    amount: 200.0,
    description: "Insurance Claim",
    date: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "20",
    accountId: "1",
    type: "DEBIT",
    amount: 18.5,
    description: "Movie Tickets",
    date: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
